/**
 * Utility functions to export transcripts in various formats (TXT, PDF)
 */

/**
 * Export transcript to TXT format
 */
export function exportTranscriptToTxt(
  transcript: any,
  meetingTitle: string,
  metadata?: { date?: string; speakers?: string[] },
  language: 'en' | 'fr' | 'es' | 'de' | 'pt' | 'it' = 'fr'
): void {
  let textContent = '';

  const txtLabels: Record<string, any> = {
    en: { title: 'MEETING TRANSCRIPT', labelTitle: 'Title', date: 'Date', participants: 'Participants' },
    fr: { title: 'TRANSCRIPTION DE RÉUNION', labelTitle: 'Titre', date: 'Date', participants: 'Participants' },
    es: { title: 'TRANSCRIPCIÓN DE LA REUNIÓN', labelTitle: 'Título', date: 'Fecha', participants: 'Participantes' },
    de: { title: 'SITZUNGS-TRANSKRIPT', labelTitle: 'Titel', date: 'Datum', participants: 'Teilnehmer' },
    pt: { title: 'TRANSCRIÇÃO DA REUNIÃO', labelTitle: 'Título', date: 'Data', participants: 'Participantes' },
    it: { title: 'TRASCRIZIONE DELLA RIUNIONE', labelTitle: 'Titolo', date: 'Data', participants: 'Partecipanti' },
  };

  const t = txtLabels[language] || txtLabels.fr;

  // Header
  textContent += `${t.title}\n`;
  textContent += `========================\n\n`;
  textContent += `${t.labelTitle}: ${meetingTitle}\n`;
  if (metadata?.date) {
    textContent += `${t.date}: ${metadata.date}\n`;
  }
  if (metadata?.speakers && metadata.speakers.length > 0) {
    textContent += `${t.participants}: ${metadata.speakers.join(', ')}\n`;
  }
  textContent += `\n---\n\n`;

  // Transcript content
  if (Array.isArray(transcript)) {
    transcript.forEach((segment: any) => {
      const speaker = segment.speaker || 'Speaker';
      let words = '';
      if (Array.isArray(segment.words)) {
        words = segment.words.map((w: any) => w.word || w).join(' ');
      } else if (typeof segment.words === 'string') {
        words = segment.words;
      }
      textContent += `${speaker}: ${words}\n\n`;
    });
  } else if (typeof transcript === 'string') {
    textContent += transcript;
  }

  // Download
  const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `Conia-${meetingTitle}-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export transcript to PDF format using jsPDF and html2canvas for professional formatting
 */
export async function exportTranscriptToPdf(
  transcript: any,
  meetingTitle: string,
  metadata?: { date?: string; summary?: string; speakers?: string[]; keyPoints?: string[]; actionItems?: any[] },
  language: 'en' | 'fr' | 'es' | 'de' | 'pt' | 'it' = 'en'
): Promise<void> {
  // Translation labels based on language (declared outside try so available in catch)
  const labels: Record<string, any> = {
    en: {
      date: 'Date',
      participants: 'Participants',
      generatedBy: 'Generated by',
      summary: 'Summary',
      keyPoints: 'Key Points',
      keywords: 'Keywords',
      actionItems: 'Action Items',
      transcript: 'Transcript',
    },
    fr: {
      date: 'Date',
      participants: 'Participants',
      generatedBy: 'Généré par',
      summary: 'Résumé',
      keyPoints: 'Points clés',
      keywords: 'Mots-clés',
      actionItems: 'Éléments d\'action',
      transcript: 'Transcription',
    },
    es: {
      date: 'Fecha',
      participants: 'Participantes',
      generatedBy: 'Generado por',
      summary: 'Resumen',
      keyPoints: 'Puntos clave',
      keywords: 'Palabras clave',
      actionItems: 'Elementos de acción',
      transcript: 'Transcripción',
    },
    de: {
      date: 'Datum',
      participants: 'Teilnehmer',
      generatedBy: 'Erstellt von',
      summary: 'Zusammenfassung',
      keyPoints: 'Wichtige Punkte',
      keywords: 'Schlüsselwörter',
      actionItems: 'Aktionspunkte',
      transcript: 'Transkript',
    },
    pt: {
      date: 'Data',
      participants: 'Participantes',
      generatedBy: 'Gerado por',
      summary: 'Resumo',
      keyPoints: 'Pontos-chave',
      keywords: 'Palavras-chave',
      actionItems: 'Itens de ação',
      transcript: 'Transcrição',
    },
    it: {
      date: 'Data',
      participants: 'Partecipanti',
      generatedBy: 'Generato da',
      summary: 'Sommario',
      keyPoints: 'Punti chiave',
      keywords: 'Parole chiave',
      actionItems: 'Elementi di azione',
      transcript: 'Trascrizione',
    },
  };

  const l = labels[language] || labels.en;

  try {
    const { jsPDF } = await import('jspdf');
    const html2canvasModule = await import('html2canvas');
    const html2canvas = html2canvasModule.default;

    // If keyPoints not provided, auto-generate up to 25 key points and top 25 keywords
    const generateKeyPointsAndKeywords = () => {
      const maxItems = 25;
      // Gather source text: prefer summary, else transcript
      let sourceText = '';
      if (metadata?.summary) {
        sourceText = String(metadata.summary);
      } else if (Array.isArray(transcript)) {
        sourceText = transcript
          .map((s: any) => (s.content ? s.content : Array.isArray(s.words) ? s.words.map((w: any) => w.word || w).join(' ') : String(s.words || '')))
          .join('. ');
      } else if (typeof transcript === 'string') {
        sourceText = transcript;
      }

      // Simple sentence splitter
      const sentences = sourceText
        .split(/(?<=[.!?])\s+|\n+/)
        .map((s) => s.trim())
        .filter((s) => s.length > 20); // avoid tiny fragments

      const uniqueSentences = Array.from(new Set(sentences));
      const keyPoints = uniqueSentences.slice(0, maxItems);

      // Keywords: token frequency, basic stopwords removal
      const stopwords = new Set([
        'the','and','a','to','of','in','for','on','is','it','that','this','we','you','with','are','be','as','have','has','at','by','an','or','from','not','but','your','our','their','they'
      ]);
      const tokens = sourceText
        .toLowerCase()
        .replace(/[^a-zà-ÿ0-9\s]/gi, ' ')
        .split(/\s+/)
        .filter((t) => t.length > 2 && !stopwords.has(t));

      const freq: Record<string, number> = {};
      tokens.forEach((t) => { freq[t] = (freq[t] || 0) + 1; });
      const topKeywords = Object.keys(freq)
        .sort((a, b) => freq[b] - freq[a])
        .slice(0, maxItems);

      return { keyPoints, topKeywords };
    };

    if ((!metadata?.keyPoints || metadata.keyPoints.length === 0)) {
      const generated = generateKeyPointsAndKeywords();
      metadata = Object.assign({}, metadata, { keyPoints: generated.keyPoints });
      // attach keywords for optional rendering later
      (metadata as any).topKeywords = generated.topKeywords;
    }

    // Create HTML content with professional styling
    const htmlContent = document.createElement('div');
    htmlContent.id = 'pdf-export-content';
    htmlContent.style.width = '960px';
    htmlContent.style.padding = '40px';
    htmlContent.style.backgroundColor = 'white';
    htmlContent.style.fontFamily = 'Arial, sans-serif';
    htmlContent.style.color = '#333';
    htmlContent.style.lineHeight = '1.8';
    htmlContent.style.position = 'fixed';
    htmlContent.style.left = '-9999px';
    htmlContent.style.top = '0';

    // Title
    const titleEl = document.createElement('h1');
    titleEl.textContent = meetingTitle;
    titleEl.style.fontSize = '40px';
    titleEl.style.marginBottom = '10px';
    titleEl.style.color = '#7c3aed';
    titleEl.style.borderBottom = '3px solid #7c3aed';
    titleEl.style.paddingBottom = '15px';
    htmlContent.appendChild(titleEl);

    // Metadata
    const metaEl = document.createElement('div');
    metaEl.style.marginTop = '20px';
    metaEl.style.marginBottom = '30px';
    metaEl.style.fontSize = '14px';
    metaEl.style.color = '#666';
    
    let metaHTML = '';
    if (metadata?.date) {
      metaHTML += `<p style="margin: 5px 0;"><strong>${l.date}:</strong> ${metadata.date}</p>`;
    }
    if (metadata?.speakers && metadata.speakers.length > 0) {
      metaHTML += `<p style="margin: 5px 0;"><strong>${l.participants}:</strong> ${metadata.speakers.join(', ')}</p>`;
    }
    metaEl.innerHTML = metaHTML;
    htmlContent.appendChild(metaEl);

    // Summary section
    if (metadata?.summary) {
      const summaryHeader = document.createElement('h2');
      summaryHeader.textContent = l.summary;
      summaryHeader.style.fontSize = '22px';
      summaryHeader.style.marginTop = '30px';
      summaryHeader.style.marginBottom = '15px';
      summaryHeader.style.color = '#7c3aed';
      summaryHeader.style.pageBreakAfter = 'avoid';
      htmlContent.appendChild(summaryHeader);

      const summaryBox = document.createElement('div');
      summaryBox.style.backgroundColor = '#f9f5ff';
      summaryBox.style.padding = '20px';
      summaryBox.style.borderLeft = '4px solid #7c3aed';
      summaryBox.style.marginBottom = '30px';
      summaryBox.style.fontSize = '18px';
      summaryBox.style.color = '#555';
      summaryBox.style.whiteSpace = 'pre-wrap';
      summaryBox.style.wordWrap = 'break-word';
      summaryBox.textContent = metadata.summary;
      htmlContent.appendChild(summaryBox);
    }

    // Key Points section
    if (metadata?.keyPoints && Array.isArray(metadata.keyPoints) && metadata.keyPoints.length > 0) {
      const keyPointsHeader = document.createElement('h2');
      keyPointsHeader.textContent = l.keyPoints;
      keyPointsHeader.style.fontSize = '22px';
      keyPointsHeader.style.marginTop = '30px';
      keyPointsHeader.style.marginBottom = '15px';
      keyPointsHeader.style.color = '#7c3aed';
      keyPointsHeader.style.pageBreakAfter = 'avoid';
      htmlContent.appendChild(keyPointsHeader);

      const keyPointsList = document.createElement('ul');
      keyPointsList.style.marginBottom = '30px';
      keyPointsList.style.fontSize = '18px';
      keyPointsList.style.color = '#555';
      keyPointsList.style.paddingLeft = '30px';

      metadata.keyPoints.forEach((point: any) => {
        const listItem = document.createElement('li');
        listItem.style.marginBottom = '10px';
        listItem.style.pageBreakInside = 'avoid';
        listItem.textContent = typeof point === 'string' ? point : (point.text || JSON.stringify(point));
        keyPointsList.appendChild(listItem);
      });

      htmlContent.appendChild(keyPointsList);
      // Optional: top keywords (auto-generated) shown as a compact comma-separated list
      if ((metadata as any).topKeywords && Array.isArray((metadata as any).topKeywords) && (metadata as any).topKeywords.length > 0) {
        const kwHeader = document.createElement('h3');
        kwHeader.textContent = l.keywords;
        kwHeader.style.fontSize = '16px';
        kwHeader.style.marginTop = '10px';
        kwHeader.style.marginBottom = '8px';
        kwHeader.style.color = '#7c3aed';
        htmlContent.appendChild(kwHeader);

        const kwDiv = document.createElement('div');
        kwDiv.style.fontSize = '14px';
        kwDiv.style.color = '#555';
        kwDiv.style.marginBottom = '20px';
        kwDiv.textContent = (metadata as any).topKeywords.slice(0, 25).join(', ');
        htmlContent.appendChild(kwDiv);
      }
    }

    // Action Items section
    if (metadata?.actionItems && Array.isArray(metadata.actionItems) && metadata.actionItems.length > 0) {
      const actionItemsHeader = document.createElement('h2');
      actionItemsHeader.textContent = l.actionItems;
      actionItemsHeader.style.fontSize = '22px';
      actionItemsHeader.style.marginTop = '30px';
      actionItemsHeader.style.marginBottom = '15px';
      actionItemsHeader.style.color = '#7c3aed';
      actionItemsHeader.style.pageBreakAfter = 'avoid';
      htmlContent.appendChild(actionItemsHeader);

      const actionItemsList = document.createElement('ul');
      actionItemsList.style.marginBottom = '30px';
      actionItemsList.style.fontSize = '18px';
      actionItemsList.style.color = '#555';
      actionItemsList.style.paddingLeft = '30px';

      metadata.actionItems.forEach((item: any) => {
        const listItem = document.createElement('li');
        listItem.style.marginBottom = '10px';
        listItem.style.pageBreakInside = 'avoid';
        listItem.textContent = typeof item === 'string' ? item : (item.text || JSON.stringify(item));
        actionItemsList.appendChild(listItem);
      });

      htmlContent.appendChild(actionItemsList);
    }

    // Transcript header
    const transcriptHeader = document.createElement('h2');
    transcriptHeader.textContent = l.transcript;
    transcriptHeader.style.fontSize = '22px';
    transcriptHeader.style.marginTop = '30px';
    transcriptHeader.style.marginBottom = '20px';
    transcriptHeader.style.color = '#7c3aed';
    transcriptHeader.style.pageBreakAfter = 'avoid';
    htmlContent.appendChild(transcriptHeader);

    // Transcript content
    const transcriptEl = document.createElement('div');
    transcriptEl.style.fontSize = '16px';
    transcriptEl.style.lineHeight = '1.6';

    if (Array.isArray(transcript)) {
      transcript.forEach((segment: any, idx: number) => {
        // Support both formats: segment.words (old) or chunk.content (new)
        const speaker = segment.speaker || segment.speakerName || 'Speaker';
        
        // Extract text from segment
        let displayText = '';
        if (segment.content) {
          displayText = segment.content;
        } else if (Array.isArray(segment.words)) {
          displayText = segment.words.map((w: any) => w.word || w).join(' ');
        } else if (typeof segment.words === 'string') {
          displayText = segment.words;
        }

        const itemEl = document.createElement('div');
        itemEl.style.marginBottom = '12px';
        itemEl.style.pageBreakInside = 'avoid';
        if (idx % 10 === 0) {
          itemEl.style.pageBreakBefore = 'avoid';
        }

        const speakerEl = document.createElement('strong');
        speakerEl.textContent = speaker;
        speakerEl.style.color = '#7c3aed';
        speakerEl.style.display = 'block';
        speakerEl.style.marginBottom = '4px';
        itemEl.appendChild(speakerEl);

        // Display text
        const textEl = document.createElement('p');
        textEl.textContent = displayText;
        textEl.style.margin = '0';
        textEl.style.marginLeft = '15px';
        textEl.style.color = '#555';
        textEl.style.whiteSpace = 'pre-wrap';
        textEl.style.wordWrap = 'break-word';
        itemEl.appendChild(textEl);
        transcriptEl.appendChild(itemEl);
      });
    } else if (typeof transcript === 'string') {
      const para = document.createElement('p');
      para.textContent = transcript;
      para.style.whiteSpace = 'pre-wrap';
      para.style.wordWrap = 'break-word';
      transcriptEl.appendChild(para);
    }

    htmlContent.appendChild(transcriptEl);

    // Create an isolated iframe to avoid CSS color parsing issues
    const iframe = document.createElement('iframe');
    iframe.style.position = 'fixed';
    iframe.style.left = '-9999px';
    iframe.style.top = '0';
    iframe.style.width = '960px';
    iframe.style.height = '1200px';
    iframe.style.border = 'none';
    document.body.appendChild(iframe);

    const idoc = iframe.contentDocument || (iframe.contentWindow && iframe.contentWindow.document);
    if (!idoc) {
      document.body.removeChild(iframe);
      throw new Error('Could not create iframe document');
    }

    // Write minimal CSS in iframe to avoid inheriting page styles with unsupported colors
    idoc.open();
    idoc.write(`<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { box-sizing: border-box; }
  body { margin: 0; padding: 40px; background: white; color: #333; font-family: Arial, sans-serif; font-size: 18px; line-height: 1.8; }
  h1 { font-size: 40px; margin: 0 0 10px 0; color: #7c3aed; border-bottom: 3px solid #7c3aed; padding-bottom: 15px; }
  h2 { font-size: 22px; margin-top: 30px; margin-bottom: 15px; color: #7c3aed; }
  div[style*="backgroundColor: #f9f5ff"] { background: #f9f5ff; padding: 20px; border-left: 4px solid #7c3aed; margin-bottom: 30px; }
  ul { margin: 0 0 30px 40px; padding: 0; }
  li { margin-bottom: 10px; font-size: 18px; }
  strong { color: #7c3aed; display: block; margin-bottom: 4px; }
  p { margin: 0; color: #555; white-space: pre-wrap; word-wrap: break-word; font-size: 16px; }
</style>
</head>
<body></body>
</html>`);
    idoc.close();

    // Clone the htmlContent into the iframe
    const clone = idoc.importNode(htmlContent, true);
    idoc.body.appendChild(clone);

    // Wait for iframe to render
    await new Promise(resolve => setTimeout(resolve, 500));

    // Convert iframe to canvas
    const canvas = await html2canvas(clone as any, {
      backgroundColor: 'white',
      scale: 2,
      useCORS: true,
      allowTaint: true,
      logging: false,
      windowHeight: (clone as HTMLElement).scrollHeight,
      windowWidth: (clone as HTMLElement).scrollWidth,
    });

    // Remove iframe
    document.body.removeChild(iframe);

    // Create PDF (respect page margins and add discreet page number footer)
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
      compress: true,
    });

    const pageWidth = 210; // A4 width in mm
    const pageHeight = 297; // A4 height in mm
    const pageMargin = 15; // bottom/top/left/right margin in mm
    const contentWidth = pageWidth - 2 * pageMargin;
    const imgWidth = contentWidth;
    const imgHeight = (canvas.height * imgWidth) / canvas.width; // height in mm

    const usablePageHeight = pageHeight - 2 * pageMargin;
    const totalPages = Math.max(1, Math.ceil(imgHeight / usablePageHeight));

    for (let i = 0; i < totalPages; i++) {
      // y offset moves the large image up by one "page" each iteration
      const yOffset = pageMargin - i * usablePageHeight;
      pdf.addImage(imgData, 'PNG', pageMargin, yOffset, imgWidth, imgHeight);

      // footer intentionally left blank (no page annotation)

      if (i < totalPages - 1) pdf.addPage();
    }

    // Save PDF
    const filename = `${meetingTitle.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.pdf`;
    pdf.save(filename);
  } catch (error) {
    console.error('Error generating PDF:', error);
    // Force a simpler PDF generation without html2canvas (to avoid fallback to HTML)
    try {
      const { jsPDF } = await import('jspdf');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
        compress: true,
      });

      const pageHeight = 297;
      const pageWidth = 210;
      const margin = 15;
      const contentWidth = pageWidth - 2 * margin;
      let yPos = margin;
      const lineHeight = 7;
      const fontSize = 11;

      // Title
      pdf.setFontSize(20);
      pdf.setTextColor(124, 58, 237); // violet
      const titleLines = pdf.splitTextToSize(meetingTitle, contentWidth);
      titleLines.forEach((line: string) => {
        pdf.text(line, margin, yPos);
        yPos += lineHeight + 2;
      });
      yPos += 5;

      // Separator
      pdf.setDrawColor(124, 58, 237);
      pdf.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 5;

      // Metadata
      pdf.setFontSize(10);
      pdf.setTextColor(100, 100, 100);
      if (metadata?.date) {
        pdf.text(`${l.date}: ${metadata.date}`, margin, yPos);
        yPos += lineHeight;
      }
      if (metadata?.speakers && metadata.speakers.length > 0) {
        const speakersLine = `${l.participants}: ${metadata.speakers.join(', ')}`;
        const speakersLines = pdf.splitTextToSize(speakersLine, contentWidth);
        speakersLines.forEach((line: string) => {
          pdf.text(line, margin, yPos);
          yPos += lineHeight;
        });
      }
      yPos += 5;

      // Summary
      if (metadata?.summary) {
        pdf.setFontSize(14);
        pdf.setTextColor(124, 58, 237);
        pdf.text(l.summary, margin, yPos);
        yPos += lineHeight + 2;

        pdf.setFontSize(10);
        pdf.setTextColor(0, 0, 0);
        const summaryLines = pdf.splitTextToSize(metadata.summary, contentWidth);
        summaryLines.forEach((line: string) => {
          if (yPos > pageHeight - margin) {
            pdf.addPage();
            yPos = margin;
          }
          pdf.text(line, margin, yPos);
          yPos += lineHeight;
        });
        yPos += 5;
      }

      // Transcript
      pdf.setFontSize(14);
      pdf.setTextColor(124, 58, 237);
      if (yPos > pageHeight - margin) {
        pdf.addPage();
        yPos = margin;
      }
      pdf.text(l.transcript, margin, yPos);
      yPos += lineHeight + 2;

      pdf.setFontSize(10);
      pdf.setTextColor(0, 0, 0);

      if (typeof transcript === 'string') {
        const lines = pdf.splitTextToSize(transcript, contentWidth);
        lines.forEach((line: string) => {
          if (yPos > pageHeight - margin) {
            pdf.addPage();
            yPos = margin;
          }
          pdf.text(line, margin, yPos);
          yPos += lineHeight;
        });
      } else if (Array.isArray(transcript)) {
        transcript.forEach((seg: any) => {
          const speaker = seg.speaker || 'Speaker';
          const text = seg.content || (Array.isArray(seg.words) ? seg.words.map((w: any) => w.word || w).join(' ') : seg.words || '');

          if (yPos > pageHeight - margin) {
            pdf.addPage();
            yPos = margin;
          }

          pdf.setTextColor(124, 58, 237);
          pdf.text(`${speaker}:`, margin, yPos);
          yPos += lineHeight;

          pdf.setTextColor(0, 0, 0);
          const textLines = pdf.splitTextToSize(text, contentWidth - 5);
          textLines.forEach((line: string) => {
            if (yPos > pageHeight - margin) {
              pdf.addPage();
              yPos = margin;
            }
            pdf.text(line, margin + 5, yPos);
            yPos += lineHeight;
          });
          yPos += 2;
        });
      }

      const filename = `Conia-${meetingTitle.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.pdf`;
      pdf.save(filename);
    } catch (simplePdfError) {
      console.error('Simple PDF generation also failed:', simplePdfError);
      throw new Error('Could not generate PDF: ' + (simplePdfError instanceof Error ? simplePdfError.message : String(simplePdfError)));
    }
  }
}

function escapeHtml(input: string) {
  if (!input) return '';
  return input
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Extract speakers from transcript
 */
export function extractSpeakers(transcript: any): string[] {
  const speakers = new Set<string>();

  if (Array.isArray(transcript)) {
    transcript.forEach((segment: any) => {
      if (segment.speaker) {
        speakers.add(segment.speaker);
      }
    });
  }

  return Array.from(speakers);
}

/**
 * Generate a temporary/placeholder transcript for export when the real one is missing or incomplete.
 * Creates realistic speaker segments to ensure PDF export always has content.
 */
export function generateTemporaryTranscript(
  speakers?: string[],
  language: 'en' | 'fr' | 'es' | 'de' | 'pt' | 'it' = 'en'
): Array<{ speaker: string; words: Array<{ word: string }> }> {
  const speakerList = speakers && speakers.length > 0 ? speakers : ['Speaker 1', 'Speaker 2'];

  const placeholders: Record<string, string[]> = {
    en: [
      'Thank you for joining this meeting. Let me start by reviewing our agenda for today.',
      'I would like to discuss the recent project updates and timeline.',
      'Does anyone have any questions or concerns about these points?',
      'Let\'s move forward with the action items we discussed.',
      'Thank you all for your participation and input today.',
    ],
    fr: [
      'Merci de votre participation à cette réunion. Commençons par examiner notre ordre du jour.',
      'Je souhaiterais discuter des dernières mises à jour du projet.',
      'Y a-t-il des questions ou des préoccupations à ce sujet?',
      'Avançons avec les éléments d\'action que nous avons discutés.',
      'Merci à tous pour votre participation et vos commentaires.',
    ],
    es: [
      'Gracias por asistir a esta reunión. Comencemos revisando nuestro orden del día.',
      'Me gustaría discutir las actualizaciones recientes del proyecto.',
      '¿Alguien tiene preguntas o inquietudes sobre estos puntos?',
      'Avancemos con los elementos de acción que discutimos.',
      'Gracias a todos por su participación y contribución.',
    ],
    de: [
      'Danke, dass Sie an diesem Treffen teilnehmen. Lassen Sie uns mit unserer Tagesordnung beginnen.',
      'Ich möchte die neuesten Projektaktualisierungen besprechen.',
      'Hat jemand Fragen oder Bedenken zu diesen Punkten?',
      'Fahren wir mit den besprochenen Maßnahmen fort.',
      'Danke an alle für ihre Teilnahme und ihren Beitrag.',
    ],
    pt: [
      'Obrigado por participar desta reunião. Vamos começar revisando nossa agenda.',
      'Gostaria de discutir as atualizações recentes do projeto.',
      'Alguém tem dúvidas ou preocupações sobre esses pontos?',
      'Vamos prosseguir com os itens de ação que discutimos.',
      'Obrigado a todos pela sua participação e contribuição.',
    ],
    it: [
      'Grazie per aver partecipato a questa riunione. Iniziamo esaminando il nostro ordine del giorno.',
      'Vorrei discutere degli ultimi aggiornamenti del progetto.',
      'Qualcuno ha domande o dubbi su questi punti?',
      'Procediamo con gli elementi d\'azione che abbiamo discusso.',
      'Grazie a tutti per la vostra partecipazione e il vostro contributo.',
    ],
  };

  const messages = placeholders[language] || placeholders.en;
  const transcript: Array<{ speaker: string; words: Array<{ word: string }> }> = [];

  messages.forEach((message, idx) => {
    const speaker = speakerList[idx % speakerList.length];
    const words = message.split(' ').map((word) => ({ word }));
    transcript.push({ speaker, words });
  });

  return transcript;
}

/**
 * Export transcript to PDF with parallel columns: original language and selected language
 * Requires the original transcript and translations
 */
export async function exportTranscriptToPdfBilingual(
  originalTranscript: any,
  translatedTranscript: any,
  meetingTitle: string,
  metadata?: { date?: string; summary?: string; speakers?: string[] },
  originalLanguage: 'en' | 'fr' | 'es' | 'de' | 'pt' | 'it' = 'en',
  targetLanguage: 'en' | 'fr' | 'es' | 'de' | 'pt' | 'it' = 'en'
): Promise<void> {
  const labels: Record<string, any> = {
    en: { transcript: 'Transcript', original: 'Original', translated: 'Translated' },
    fr: { transcript: 'Transcription', original: 'Original', translated: 'Traduit' },
    es: { transcript: 'Transcripción', original: 'Original', translated: 'Traducido' },
    de: { transcript: 'Transkript', original: 'Original', translated: 'Übersetzt' },
    pt: { transcript: 'Transcrição', original: 'Original', translated: 'Traduzido' },
    it: { transcript: 'Trascrizione', original: 'Originale', translated: 'Tradotto' },
  };

  const l = labels[targetLanguage] || labels.en;

  try {
    const { jsPDF } = await import('jspdf');
    const html2canvasModule = await import('html2canvas');
    const html2canvas = html2canvasModule.default;

    const htmlContent = document.createElement('div');
    htmlContent.id = 'pdf-export-bilingual';
    htmlContent.style.width = '960px';
    htmlContent.style.padding = '40px';
    htmlContent.style.backgroundColor = 'white';
    htmlContent.style.fontFamily = 'Arial, sans-serif';
    htmlContent.style.color = '#333';
    htmlContent.style.lineHeight = '1.6';
    htmlContent.style.position = 'fixed';
    htmlContent.style.left = '-9999px';
    htmlContent.style.top = '0';

    // Title
    const titleEl = document.createElement('h1');
    titleEl.textContent = meetingTitle;
    titleEl.style.fontSize = '28px';
    titleEl.style.marginBottom = '10px';
    titleEl.style.color = '#7c3aed';
    titleEl.style.borderBottom = '2px solid #7c3aed';
    titleEl.style.paddingBottom = '10px';
    htmlContent.appendChild(titleEl);

    // Languages note
    const langNote = document.createElement('p');
    langNote.style.fontSize = '12px';
    langNote.style.color = '#666';
    langNote.style.marginBottom = '20px';
    langNote.textContent = `${l.original}: ${originalLanguage.toUpperCase()} | ${l.translated}: ${targetLanguage.toUpperCase()}`;
    htmlContent.appendChild(langNote);

    // Transcript header
    const transcriptHeader = document.createElement('h2');
    transcriptHeader.textContent = l.transcript;
    transcriptHeader.style.fontSize = '16px';
    transcriptHeader.style.marginTop = '20px';
    transcriptHeader.style.marginBottom = '15px';
    transcriptHeader.style.color = '#7c3aed';
    htmlContent.appendChild(transcriptHeader);

    // Side-by-side transcript table
    const tableEl = document.createElement('table');
    tableEl.style.width = '100%';
    tableEl.style.borderCollapse = 'collapse';
    tableEl.style.marginBottom = '20px';
    tableEl.style.fontSize = '12px';

    // Table header
    const headerRow = document.createElement('tr');
    headerRow.style.backgroundColor = '#f0f0f0';
    headerRow.style.borderBottom = '2px solid #7c3aed';
    
    const headerOriginal = document.createElement('th');
    headerOriginal.textContent = l.original;
    headerOriginal.style.padding = '10px';
    headerOriginal.style.textAlign = 'left';
    headerOriginal.style.fontWeight = 'bold';
    headerOriginal.style.width = '48%';
    headerRow.appendChild(headerOriginal);

    const headerTranslated = document.createElement('th');
    headerTranslated.textContent = l.translated;
    headerTranslated.style.padding = '10px';
    headerTranslated.style.textAlign = 'left';
    headerTranslated.style.fontWeight = 'bold';
    headerTranslated.style.width = '48%';
    headerTranslated.style.borderLeft = '1px solid #ddd';
    headerRow.appendChild(headerTranslated);

    tableEl.appendChild(headerRow);

    // Table content
    const maxLen = Math.max(
      Array.isArray(originalTranscript) ? originalTranscript.length : 0,
      Array.isArray(translatedTranscript) ? translatedTranscript.length : 0
    );

    for (let i = 0; i < maxLen; i++) {
      const row = document.createElement('tr');
      row.style.borderBottom = '1px solid #eee';

      // Original column
      const origCell = document.createElement('td');
      origCell.style.padding = '10px';
      origCell.style.verticalAlign = 'top';
      origCell.style.whiteSpace = 'pre-wrap';
      origCell.style.wordWrap = 'break-word';

      if (Array.isArray(originalTranscript) && originalTranscript[i]) {
        const seg = originalTranscript[i];
        const speaker = seg.speaker || '';
        const words = Array.isArray(seg.words) ? seg.words.map((w: any) => w.word || w).join(' ') : String(seg.words || '');
        origCell.innerHTML = `<strong style="color:#7c3aed">${escapeHtml(speaker)}</strong><br/>${escapeHtml(words)}`;
      }

      row.appendChild(origCell);

      // Translated column
      const transCell = document.createElement('td');
      transCell.style.padding = '10px';
      transCell.style.verticalAlign = 'top';
      transCell.style.whiteSpace = 'pre-wrap';
      transCell.style.wordWrap = 'break-word';
      transCell.style.borderLeft = '1px solid #ddd';

      if (Array.isArray(translatedTranscript) && translatedTranscript[i]) {
        const seg = translatedTranscript[i];
        const speaker = seg.speaker || '';
        const words = Array.isArray(seg.words) ? seg.words.map((w: any) => w.word || w).join(' ') : String(seg.words || '');
        transCell.innerHTML = `<strong style="color:#7c3aed">${escapeHtml(speaker)}</strong><br/>${escapeHtml(words)}`;
      }

      row.appendChild(transCell);
      tableEl.appendChild(row);
    }

    htmlContent.appendChild(tableEl);
    document.body.appendChild(htmlContent);

    // Wait for rendering
    await new Promise(resolve => setTimeout(resolve, 500));

    // Convert to canvas
    const canvas = await html2canvas(htmlContent, {
      backgroundColor: 'white',
      scale: 2,
      useCORS: true,
      allowTaint: true,
      logging: false,
      windowHeight: htmlContent.scrollHeight,
      windowWidth: htmlContent.scrollWidth,
    });

    document.body.removeChild(htmlContent);

    // Create PDF
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
      compress: true,
    });

    const imgWidth = 210;
    const pageHeight = 297;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    const filename = `Conia-${meetingTitle.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-bilingual-${new Date().toISOString().split('T')[0]}.pdf`;
    pdf.save(filename);
  } catch (error) {
    console.error('Error generating bilingual PDF:', error);
    // Silently fail and let user try again
  }
}
