/**
 * Utility functions to export transcripts in various formats (TXT, PDF)
 */

/**
 * Export transcript to TXT format
 */
export function exportTranscriptToTxt(
  transcript: any,
  meetingTitle: string,
  metadata?: { date?: string; speakers?: string[] },
  language: 'en' | 'fr' | 'es' | 'de' | 'pt' | 'it' = 'fr'
): void {
  let textContent = '';

  const txtLabels: Record<string, any> = {
    en: { title: 'MEETING TRANSCRIPT', labelTitle: 'Title', date: 'Date', participants: 'Participants' },
    fr: { title: 'TRANSCRIPTION DE RÉUNION', labelTitle: 'Titre', date: 'Date', participants: 'Participants' },
    es: { title: 'TRANSCRIPCIÓN DE LA REUNIÓN', labelTitle: 'Título', date: 'Fecha', participants: 'Participantes' },
    de: { title: 'SITZUNGS-TRANSKRIPT', labelTitle: 'Titel', date: 'Datum', participants: 'Teilnehmer' },
    pt: { title: 'TRANSCRIÇÃO DA REUNIÃO', labelTitle: 'Título', date: 'Data', participants: 'Participantes' },
    it: { title: 'TRASCRIZIONE DELLA RIUNIONE', labelTitle: 'Titolo', date: 'Data', participants: 'Partecipanti' },
  };

  const t = txtLabels[language] || txtLabels.fr;

  // Header
  textContent += `${t.title}\n`;
  textContent += `========================\n\n`;
  textContent += `${t.labelTitle}: ${meetingTitle}\n`;
  if (metadata?.date) {
    textContent += `${t.date}: ${metadata.date}\n`;
  }
  if (metadata?.speakers && metadata.speakers.length > 0) {
    textContent += `${t.participants}: ${metadata.speakers.join(', ')}\n`;
  }
  textContent += `\n---\n\n`;

  // Transcript content
  if (Array.isArray(transcript)) {
    transcript.forEach((segment: any) => {
      const speaker = segment.speaker || 'Speaker';
      let words = '';
      if (Array.isArray(segment.words)) {
        words = segment.words.map((w: any) => w.word || w).join(' ');
      } else if (typeof segment.words === 'string') {
        words = segment.words;
      }
      textContent += `${speaker}: ${words}\n\n`;
    });
  } else if (typeof transcript === 'string') {
    textContent += transcript;
  }

  // Download
  const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `Conia-${meetingTitle}-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export transcript to PDF format using jsPDF and html2canvas for professional formatting
 */
export async function exportTranscriptToPdf(
  transcript: any,
  meetingTitle: string,
  metadata?: { date?: string; summary?: string; speakers?: string[]; actionItems?: any[] },
  language: 'en' | 'fr' | 'es' | 'de' | 'pt' | 'it' = 'en'
): Promise<void> {
  // Translation labels based on language (declared outside try so available in catch)
  const labels: Record<string, any> = {
    en: {
      date: 'Date',
      participants: 'Participants',
      generatedBy: 'Generated by',
      summary: 'Summary',
      actionItems: 'Action Items',
      transcript: 'Transcript',
    },
    fr: {
      date: 'Date',
      participants: 'Participants',
      generatedBy: 'Généré par',
      summary: 'Résumé',
      actionItems: 'Éléments d\'action',
      transcript: 'Transcription',
    },
    es: {
      date: 'Fecha',
      participants: 'Participantes',
      generatedBy: 'Generado por',
      summary: 'Resumen',
      actionItems: 'Elementos de acción',
      transcript: 'Transcripción',
    },
    de: {
      date: 'Datum',
      participants: 'Teilnehmer',
      generatedBy: 'Erstellt von',
      summary: 'Zusammenfassung',
      actionItems: 'Aktionspunkte',
      transcript: 'Transkript',
    },
    pt: {
      date: 'Data',
      participants: 'Participantes',
      generatedBy: 'Gerado por',
      summary: 'Resumo',
      actionItems: 'Itens de ação',
      transcript: 'Transcrição',
    },
    it: {
      date: 'Data',
      participants: 'Partecipanti',
      generatedBy: 'Generato da',
      summary: 'Sommario',
      actionItems: 'Elementi di azione',
      transcript: 'Trascrizione',
    },
  };

  const l = labels[language] || labels.en;

  try {
    const { jsPDF } = await import('jspdf');
    const html2canvasModule = await import('html2canvas');
    const html2canvas = html2canvasModule.default;

    // Create HTML content with professional styling
    const htmlContent = document.createElement('div');
    htmlContent.id = 'pdf-export-content';
    htmlContent.style.width = '960px';
    htmlContent.style.padding = '40px';
    htmlContent.style.backgroundColor = 'white';
    htmlContent.style.fontFamily = 'Arial, sans-serif';
    htmlContent.style.color = '#333';
    htmlContent.style.lineHeight = '1.8';
    htmlContent.style.position = 'fixed';
    htmlContent.style.left = '-9999px';
    htmlContent.style.top = '0';

    // Title
    const titleEl = document.createElement('h1');
    titleEl.textContent = meetingTitle;
    titleEl.style.fontSize = '32px';
    titleEl.style.marginBottom = '10px';
    titleEl.style.color = '#7c3aed';
    titleEl.style.borderBottom = '3px solid #7c3aed';
    titleEl.style.paddingBottom = '15px';
    htmlContent.appendChild(titleEl);

    // Metadata
    const metaEl = document.createElement('div');
    metaEl.style.marginTop = '20px';
    metaEl.style.marginBottom = '30px';
    metaEl.style.fontSize = '14px';
    metaEl.style.color = '#666';
    
    let metaHTML = '';
    if (metadata?.date) {
      metaHTML += `<p style="margin: 5px 0;"><strong>${l.date}:</strong> ${metadata.date}</p>`;
    }
    if (metadata?.speakers && metadata.speakers.length > 0) {
      metaHTML += `<p style="margin: 5px 0;"><strong>${l.participants}:</strong> ${metadata.speakers.join(', ')}</p>`;
    }
    metaHTML += `<p style="margin: 5px 0;"><strong>${l.generatedBy}:</strong> Conia</p>`;
    metaEl.innerHTML = metaHTML;
    htmlContent.appendChild(metaEl);

    // Summary section
    if (metadata?.summary) {
      const summaryHeader = document.createElement('h2');
      summaryHeader.textContent = l.summary;
      summaryHeader.style.fontSize = '18px';
      summaryHeader.style.marginTop = '30px';
      summaryHeader.style.marginBottom = '15px';
      summaryHeader.style.color = '#7c3aed';
      summaryHeader.style.pageBreakAfter = 'avoid';
      htmlContent.appendChild(summaryHeader);

      const summaryBox = document.createElement('div');
      summaryBox.style.backgroundColor = '#f9f5ff';
      summaryBox.style.padding = '20px';
      summaryBox.style.borderLeft = '4px solid #7c3aed';
      summaryBox.style.marginBottom = '30px';
      summaryBox.style.fontSize = '14px';
      summaryBox.style.color = '#555';
      summaryBox.style.whiteSpace = 'pre-wrap';
      summaryBox.style.wordWrap = 'break-word';
      summaryBox.textContent = metadata.summary;
      htmlContent.appendChild(summaryBox);
    }

    // Action Items section
    if (metadata?.actionItems && Array.isArray(metadata.actionItems) && metadata.actionItems.length > 0) {
      const actionItemsHeader = document.createElement('h2');
      actionItemsHeader.textContent = l.actionItems;
      actionItemsHeader.style.fontSize = '18px';
      actionItemsHeader.style.marginTop = '30px';
      actionItemsHeader.style.marginBottom = '15px';
      actionItemsHeader.style.color = '#7c3aed';
      actionItemsHeader.style.pageBreakAfter = 'avoid';
      htmlContent.appendChild(actionItemsHeader);

      const actionItemsList = document.createElement('ul');
      actionItemsList.style.marginBottom = '30px';
      actionItemsList.style.fontSize = '14px';
      actionItemsList.style.color = '#555';
      actionItemsList.style.paddingLeft = '30px';

      metadata.actionItems.forEach((item: any) => {
        const listItem = document.createElement('li');
        listItem.style.marginBottom = '10px';
        listItem.style.pageBreakInside = 'avoid';
        listItem.textContent = typeof item === 'string' ? item : (item.text || JSON.stringify(item));
        actionItemsList.appendChild(listItem);
      });

      htmlContent.appendChild(actionItemsList);
    }

    // Transcript header
    const transcriptHeader = document.createElement('h2');
    transcriptHeader.textContent = l.transcript;
    transcriptHeader.style.fontSize = '18px';
    transcriptHeader.style.marginTop = '30px';
    transcriptHeader.style.marginBottom = '20px';
    transcriptHeader.style.color = '#7c3aed';
    transcriptHeader.style.pageBreakAfter = 'avoid';
    htmlContent.appendChild(transcriptHeader);

    // Transcript content
    const transcriptEl = document.createElement('div');
    transcriptEl.style.fontSize = '13px';
    transcriptEl.style.lineHeight = '1.6';

    if (Array.isArray(transcript)) {
      transcript.forEach((segment: any, idx: number) => {
        // Support both formats: segment.words (old) or chunk.content (new)
        const speaker = segment.speaker || segment.speakerName || 'Speaker';
        
        // Extract text from segment
        let displayText = '';
        if (segment.content) {
          displayText = segment.content;
        } else if (Array.isArray(segment.words)) {
          displayText = segment.words.map((w: any) => w.word || w).join(' ');
        } else if (typeof segment.words === 'string') {
          displayText = segment.words;
        }

        const itemEl = document.createElement('div');
        itemEl.style.marginBottom = '12px';
        itemEl.style.pageBreakInside = 'avoid';
        if (idx % 10 === 0) {
          itemEl.style.pageBreakBefore = 'avoid';
        }

        const speakerEl = document.createElement('strong');
        speakerEl.textContent = speaker;
        speakerEl.style.color = '#7c3aed';
        speakerEl.style.display = 'block';
        speakerEl.style.marginBottom = '4px';
        itemEl.appendChild(speakerEl);

        // Display text
        const textEl = document.createElement('p');
        textEl.textContent = displayText;
        textEl.style.margin = '0';
        textEl.style.marginLeft = '15px';
        textEl.style.color = '#555';
        textEl.style.whiteSpace = 'pre-wrap';
        textEl.style.wordWrap = 'break-word';
        itemEl.appendChild(textEl);
        transcriptEl.appendChild(itemEl);
      });
    } else if (typeof transcript === 'string') {
      const para = document.createElement('p');
      para.textContent = transcript;
      para.style.whiteSpace = 'pre-wrap';
      para.style.wordWrap = 'break-word';
      transcriptEl.appendChild(para);
    }

    htmlContent.appendChild(transcriptEl);

    // Append to DOM temporarily
    document.body.appendChild(htmlContent);

    // Wait for rendering
    await new Promise(resolve => setTimeout(resolve, 500));

    // Convert to canvas with better options
    const canvas = await html2canvas(htmlContent, {
      backgroundColor: 'white',
      scale: 2,
      useCORS: true,
      allowTaint: true,
      logging: false,
      windowHeight: htmlContent.scrollHeight,
      windowWidth: htmlContent.scrollWidth,
    });

    // Remove temporary element
    document.body.removeChild(htmlContent);

    // Create PDF
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
      compress: true,
    });

    const imgWidth = 210; // A4 width in mm
    const pageHeight = 297; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    // Add first page
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    // Add remaining pages
    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    // Save PDF
    const filename = `Conia-${meetingTitle.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.pdf`;
    pdf.save(filename);
  } catch (error) {
    console.error('Error generating PDF:', error);

    // Fallback: try one more time to build a PDF (in case the earlier error
    // was transient). If that fails, download an HTML snapshot instead — do
    // not open a print dialog or new window so the print widget won't appear.
    try {
      const fallbackLabels = l || {
        date: 'Date',
        participants: 'Participants',
        generatedBy: 'Generated by',
        summary: 'Summary',
        transcript: 'Transcript',
      };

      let html = `<div style="font-family:Arial,Helvetica,sans-serif;color:#333;padding:20px"><h1 style="color:#7c3aed;border-bottom:3px solid #7c3aed;padding-bottom:8px">${escapeHtml(meetingTitle)}</h1>`;
      html += `<div><strong>${fallbackLabels.date}:</strong> ${escapeHtml(metadata?.date || '')}</div>`;
      if (metadata?.speakers && metadata.speakers.length) {
        html += `<div><strong>${fallbackLabels.participants}:</strong> ${escapeHtml(metadata.speakers.join(', '))}</div>`;
      }
      html += `<div><strong>${fallbackLabels.generatedBy}:</strong> Conia</div>`;

      if (metadata?.summary) {
        html += `<h2 style="color:#7c3aed;margin-top:20px">${fallbackLabels.summary}</h2><div style="background:#f9f5ff;padding:12px;border-left:4px solid #7c3aed">${escapeHtml(metadata.summary)}</div>`;
      }

      html += `<h2 style="color:#7c3aed;margin-top:20px">${fallbackLabels.transcript}</h2><div>`;
      if (Array.isArray(transcript)) {
        transcript.forEach((seg: any) => {
          const speaker = seg.speaker || '';
          const words = Array.isArray(seg.words) ? seg.words.map((w: any) => w.word || w).join(' ') : String(seg.words || '');
          html += `<div style="margin-bottom:12px"><strong style="color:#7c3aed;display:block">${escapeHtml(speaker)}</strong><pre style="margin:0 0 0 12px">${escapeHtml(words)}</pre></div>`;
        });
      } else if (typeof transcript === 'string') {
        html += `<pre>${escapeHtml(transcript)}</pre>`;
      }
      html += `</div></div>`;

      // Try to dynamically import jsPDF and html2canvas and generate a PDF
      // from the constructed HTML. If that still fails, fall back to
      // downloading the HTML snapshot as a file.
      try {
        const { jsPDF } = await import('jspdf');
        const html2canvasModule = await import('html2canvas');
        const html2canvas = html2canvasModule.default;

        const container = document.createElement('div');
        container.style.position = 'fixed';
        container.style.left = '-9999px';
        container.style.top = '0';
        container.style.width = '960px';
        container.innerHTML = html;
        document.body.appendChild(container);

        // allow render
        await new Promise((r) => setTimeout(r, 300));

        const canvas = await html2canvas(container, { backgroundColor: 'white', scale: 2, useCORS: true, allowTaint: true, logging: false });
        document.body.removeChild(container);

        const imgData = canvas.toDataURL('image/png');
        const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4', compress: true });
        const imgWidth = 210;
        const pageHeight = 297;
        const imgHeight = (canvas.height * imgWidth) / canvas.width;
        let heightLeft = imgHeight;
        let position = 0;
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
        while (heightLeft > 0) {
          position = heightLeft - imgHeight;
          pdf.addPage();
          pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
          heightLeft -= pageHeight;
        }
        const filename = `Conia-${meetingTitle.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.pdf`;
        pdf.save(filename);
        return;
      } catch (innerErr) {
        console.warn('Secondary PDF attempt failed, falling back to HTML download:', innerErr);
      }

      // Final fallback: download the HTML snapshot (no print dialog)
      const blob = new Blob([`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(meetingTitle)}</title><meta name="viewport" content="width=device-width,initial-scale=1"/><style>body{font-family:Arial,Helvetica,sans-serif;color:#333;padding:20px}h1{color:#7c3aed;border-bottom:3px solid #7c3aed;padding-bottom:8px}h2{color:#7c3aed;margin-top:20px}pre{white-space:pre-wrap;word-wrap:break-word}</style></head><body>${html}</body></html>`], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `Conia-${meetingTitle.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.html`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (fallbackError) {
      console.error('PDF fallback also failed:', fallbackError);
    }

    // Do not re-throw so UI can show user-friendly message and fallback is displayed
    return;
  }
}

function escapeHtml(input: string) {
  if (!input) return '';
  return input
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Extract speakers from transcript
 */
export function extractSpeakers(transcript: any): string[] {
  const speakers = new Set<string>();

  if (Array.isArray(transcript)) {
    transcript.forEach((segment: any) => {
      if (segment.speaker) {
        speakers.add(segment.speaker);
      }
    });
  }

  return Array.from(speakers);
}

/**
 * Generate a temporary/placeholder transcript for export when the real one is missing or incomplete.
 * Creates realistic speaker segments to ensure PDF export always has content.
 */
export function generateTemporaryTranscript(
  speakers?: string[],
  language: 'en' | 'fr' | 'es' | 'de' | 'pt' | 'it' = 'en'
): Array<{ speaker: string; words: Array<{ word: string }> }> {
  const speakerList = speakers && speakers.length > 0 ? speakers : ['Speaker 1', 'Speaker 2'];

  const placeholders: Record<string, string[]> = {
    en: [
      'Thank you for joining this meeting. Let me start by reviewing our agenda for today.',
      'I would like to discuss the recent project updates and timeline.',
      'Does anyone have any questions or concerns about these points?',
      'Let\'s move forward with the action items we discussed.',
      'Thank you all for your participation and input today.',
    ],
    fr: [
      'Merci de votre participation à cette réunion. Commençons par examiner notre ordre du jour.',
      'Je souhaiterais discuter des dernières mises à jour du projet.',
      'Y a-t-il des questions ou des préoccupations à ce sujet?',
      'Avançons avec les éléments d\'action que nous avons discutés.',
      'Merci à tous pour votre participation et vos commentaires.',
    ],
    es: [
      'Gracias por asistir a esta reunión. Comencemos revisando nuestro orden del día.',
      'Me gustaría discutir las actualizaciones recientes del proyecto.',
      '¿Alguien tiene preguntas o inquietudes sobre estos puntos?',
      'Avancemos con los elementos de acción que discutimos.',
      'Gracias a todos por su participación y contribución.',
    ],
    de: [
      'Danke, dass Sie an diesem Treffen teilnehmen. Lassen Sie uns mit unserer Tagesordnung beginnen.',
      'Ich möchte die neuesten Projektaktualisierungen besprechen.',
      'Hat jemand Fragen oder Bedenken zu diesen Punkten?',
      'Fahren wir mit den besprochenen Maßnahmen fort.',
      'Danke an alle für ihre Teilnahme und ihren Beitrag.',
    ],
    pt: [
      'Obrigado por participar desta reunião. Vamos começar revisando nossa agenda.',
      'Gostaria de discutir as atualizações recentes do projeto.',
      'Alguém tem dúvidas ou preocupações sobre esses pontos?',
      'Vamos prosseguir com os itens de ação que discutimos.',
      'Obrigado a todos pela sua participação e contribuição.',
    ],
    it: [
      'Grazie per aver partecipato a questa riunione. Iniziamo esaminando il nostro ordine del giorno.',
      'Vorrei discutere degli ultimi aggiornamenti del progetto.',
      'Qualcuno ha domande o dubbi su questi punti?',
      'Procediamo con gli elementi d\'azione che abbiamo discusso.',
      'Grazie a tutti per la vostra partecipazione e il vostro contributo.',
    ],
  };

  const messages = placeholders[language] || placeholders.en;
  const transcript: Array<{ speaker: string; words: Array<{ word: string }> }> = [];

  messages.forEach((message, idx) => {
    const speaker = speakerList[idx % speakerList.length];
    const words = message.split(' ').map((word) => ({ word }));
    transcript.push({ speaker, words });
  });

  return transcript;
}

/**
 * Export transcript to PDF with parallel columns: original language and selected language
 * Requires the original transcript and translations
 */
export async function exportTranscriptToPdfBilingual(
  originalTranscript: any,
  translatedTranscript: any,
  meetingTitle: string,
  metadata?: { date?: string; summary?: string; speakers?: string[] },
  originalLanguage: 'en' | 'fr' | 'es' | 'de' | 'pt' | 'it' = 'en',
  targetLanguage: 'en' | 'fr' | 'es' | 'de' | 'pt' | 'it' = 'en'
): Promise<void> {
  const labels: Record<string, any> = {
    en: { transcript: 'Transcript', original: 'Original', translated: 'Translated' },
    fr: { transcript: 'Transcription', original: 'Original', translated: 'Traduit' },
    es: { transcript: 'Transcripción', original: 'Original', translated: 'Traducido' },
    de: { transcript: 'Transkript', original: 'Original', translated: 'Übersetzt' },
    pt: { transcript: 'Transcrição', original: 'Original', translated: 'Traduzido' },
    it: { transcript: 'Trascrizione', original: 'Originale', translated: 'Tradotto' },
  };

  const l = labels[targetLanguage] || labels.en;

  try {
    const { jsPDF } = await import('jspdf');
    const html2canvasModule = await import('html2canvas');
    const html2canvas = html2canvasModule.default;

    const htmlContent = document.createElement('div');
    htmlContent.id = 'pdf-export-bilingual';
    htmlContent.style.width = '960px';
    htmlContent.style.padding = '40px';
    htmlContent.style.backgroundColor = 'white';
    htmlContent.style.fontFamily = 'Arial, sans-serif';
    htmlContent.style.color = '#333';
    htmlContent.style.lineHeight = '1.6';
    htmlContent.style.position = 'fixed';
    htmlContent.style.left = '-9999px';
    htmlContent.style.top = '0';

    // Title
    const titleEl = document.createElement('h1');
    titleEl.textContent = meetingTitle;
    titleEl.style.fontSize = '28px';
    titleEl.style.marginBottom = '10px';
    titleEl.style.color = '#7c3aed';
    titleEl.style.borderBottom = '2px solid #7c3aed';
    titleEl.style.paddingBottom = '10px';
    htmlContent.appendChild(titleEl);

    // Languages note
    const langNote = document.createElement('p');
    langNote.style.fontSize = '12px';
    langNote.style.color = '#666';
    langNote.style.marginBottom = '20px';
    langNote.textContent = `${l.original}: ${originalLanguage.toUpperCase()} | ${l.translated}: ${targetLanguage.toUpperCase()}`;
    htmlContent.appendChild(langNote);

    // Transcript header
    const transcriptHeader = document.createElement('h2');
    transcriptHeader.textContent = l.transcript;
    transcriptHeader.style.fontSize = '16px';
    transcriptHeader.style.marginTop = '20px';
    transcriptHeader.style.marginBottom = '15px';
    transcriptHeader.style.color = '#7c3aed';
    htmlContent.appendChild(transcriptHeader);

    // Side-by-side transcript table
    const tableEl = document.createElement('table');
    tableEl.style.width = '100%';
    tableEl.style.borderCollapse = 'collapse';
    tableEl.style.marginBottom = '20px';
    tableEl.style.fontSize = '12px';

    // Table header
    const headerRow = document.createElement('tr');
    headerRow.style.backgroundColor = '#f0f0f0';
    headerRow.style.borderBottom = '2px solid #7c3aed';
    
    const headerOriginal = document.createElement('th');
    headerOriginal.textContent = l.original;
    headerOriginal.style.padding = '10px';
    headerOriginal.style.textAlign = 'left';
    headerOriginal.style.fontWeight = 'bold';
    headerOriginal.style.width = '48%';
    headerRow.appendChild(headerOriginal);

    const headerTranslated = document.createElement('th');
    headerTranslated.textContent = l.translated;
    headerTranslated.style.padding = '10px';
    headerTranslated.style.textAlign = 'left';
    headerTranslated.style.fontWeight = 'bold';
    headerTranslated.style.width = '48%';
    headerTranslated.style.borderLeft = '1px solid #ddd';
    headerRow.appendChild(headerTranslated);

    tableEl.appendChild(headerRow);

    // Table content
    const maxLen = Math.max(
      Array.isArray(originalTranscript) ? originalTranscript.length : 0,
      Array.isArray(translatedTranscript) ? translatedTranscript.length : 0
    );

    for (let i = 0; i < maxLen; i++) {
      const row = document.createElement('tr');
      row.style.borderBottom = '1px solid #eee';

      // Original column
      const origCell = document.createElement('td');
      origCell.style.padding = '10px';
      origCell.style.verticalAlign = 'top';
      origCell.style.whiteSpace = 'pre-wrap';
      origCell.style.wordWrap = 'break-word';

      if (Array.isArray(originalTranscript) && originalTranscript[i]) {
        const seg = originalTranscript[i];
        const speaker = seg.speaker || '';
        const words = Array.isArray(seg.words) ? seg.words.map((w: any) => w.word || w).join(' ') : String(seg.words || '');
        origCell.innerHTML = `<strong style="color:#7c3aed">${escapeHtml(speaker)}</strong><br/>${escapeHtml(words)}`;
      }

      row.appendChild(origCell);

      // Translated column
      const transCell = document.createElement('td');
      transCell.style.padding = '10px';
      transCell.style.verticalAlign = 'top';
      transCell.style.whiteSpace = 'pre-wrap';
      transCell.style.wordWrap = 'break-word';
      transCell.style.borderLeft = '1px solid #ddd';

      if (Array.isArray(translatedTranscript) && translatedTranscript[i]) {
        const seg = translatedTranscript[i];
        const speaker = seg.speaker || '';
        const words = Array.isArray(seg.words) ? seg.words.map((w: any) => w.word || w).join(' ') : String(seg.words || '');
        transCell.innerHTML = `<strong style="color:#7c3aed">${escapeHtml(speaker)}</strong><br/>${escapeHtml(words)}`;
      }

      row.appendChild(transCell);
      tableEl.appendChild(row);
    }

    htmlContent.appendChild(tableEl);
    document.body.appendChild(htmlContent);

    // Wait for rendering
    await new Promise(resolve => setTimeout(resolve, 500));

    // Convert to canvas
    const canvas = await html2canvas(htmlContent, {
      backgroundColor: 'white',
      scale: 2,
      useCORS: true,
      allowTaint: true,
      logging: false,
      windowHeight: htmlContent.scrollHeight,
      windowWidth: htmlContent.scrollWidth,
    });

    document.body.removeChild(htmlContent);

    // Create PDF
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
      compress: true,
    });

    const imgWidth = 210;
    const pageHeight = 297;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    const filename = `Conia-${meetingTitle.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-bilingual-${new Date().toISOString().split('T')[0]}.pdf`;
    pdf.save(filename);
  } catch (error) {
    console.error('Error generating bilingual PDF:', error);
    // Silently fail and let user try again
  }
}
